import { faAngleDoubleLeft, faAngleDoubleRight, faAngleLeft, faAngleRight, faBan, faBox, faBoxesStacked, faCalendarCheck, faCancel, faCartArrowDown, faChartLine, faChartPie, faChartSimple, faCloudDownload, faCloudUpload, faCog, faCubesStacked, faDollar, faDownload, faFlag, faGlobeEurope, faHome, faHourglassHalf, faInfoCircle, faList, faLock, faMapMarkedAlt, faPencil, faPencilAlt, faPhoneAlt, faPlus, faQrcode, faSave, faSearch, faShoppingBasket, faTools, faTrash, faTruck, faUpload, faUserCog, faUsers } from '@fortawesome/free-solid-svg-icons';
import { IconDefinition } from '@fortawesome/fontawesome-svg-core';

export const Icons: { [key: string]: IconDefinition } = {
  faChartLine,
  faChartPie,
  faChartSimple,
  faBoxesStacked,
  faUsers,
  faShoppingBasket,
  faCog,
  faTruck,
  faUserCog,
  faTools,
  faCubesStacked,
  faSearch,
  faInfoCircle,
  faDollar,
  faFlag,
  faPencil,
  faTrash,
  faList,
  faAngleDoubleLeft,
  faAngleDoubleRight,
  faAngleLeft,
  faAngleRight,
  faPlus,
  faCloudUpload,
  faCloudDownload,
  faSave,
  faCancel,
  faBox,
  faBan,
  faPhoneAlt,
  faHome,
  faMapMarkedAlt,
  faGlobeEurope,
  faQrcode,
  faCalendarCheck,
  faCartArrowDown,
  faHourglassHalf,
  faPencilAlt,
  faLock
};
